apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoUrl }}
    targetRevision: HEAD
    path: bootstrap-cluster
    helm:
      parameters:
        - name: repoUrl
          value: {{ $.Values.repoUrl }}
        - name: domain
          value: {{ $.Values.domain }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
