apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secret
spec:
    secretTemplates:
        - name: argocd-secret
          data:
            admin.password: ENC[AES256_GCM,data:etJbzWpK20N4AMuzfzXNpf4ZbuEIi21mpyaH/95XFqeUmFgaVkv97qchnrQ+eddCbhAvFspElOB6iCVl0wt/RmDWNMZW6JWJJe1bLzs+Jrs=,iv:VwndjefoTVKcuSo7jGwPvKlTeLpmgNwmxdA0kX/BKa0=,tag:LtfZflTu8VFIGYOA0dPcFw==,type:str]
            server.secretkey: ENC[AES256_GCM,data:eoru1UQSqcG8E257kz8BAWJzI9U04W7LsyEG5p8lzikq7T4vXxZ0SBzmk0h8WUDzMeD6SSuVUkMgVUwokV8/3wrIugHgspSAIKIe3RY5teY=,iv:PFRMS0zN9tlueFRSdX54U1PtYy4U8wucNhjzrlu7tys=,tag:qutUp8ivsdu1GlWy5mo80g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZGRvcU1ZRVlBa3FwMFpo
            SmtTNDNqK0xvWjVYRlRiVGkxYTlwYkpiM1UwCk1IczhsTWdydmVNdTJpMENIWVBp
            ZFFWb09YV1BUS3dCREdhMi9KSG0wL00KLS0tIE43YVhOZWozVno5d3Z1bFNNT2Jp
            STVoeTF1Ym9EMStwalpIbU1FUTAwQTQKR8S9v20blDxO6SdXy5HTe7D6Wd0knqW1
            KMkmeBVS0uNNMkUgo9JIi6ASiH14LW3ADAGPw0sM5pIAkSrdps1xFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-16T12:46:34Z"
    mac: ENC[AES256_GCM,data:trEnHvb+VEfeTGtfdKgnZ/CvNMybGkMiZB4pKaYHSLlaPT7E/RsiKVWyTBLvSS+9EKwbzu9u3zVqXBuHLaaLTB6XTDZnOrCgWcn/GEl2F4SfNbR5aCVaHhYFJ6qk6szBoFrgwUt1AsRJgQC5M3gCEqz/z+yonf1BECLprAksixQ=,iv:EXpRMBHdEzWKtitEaQDEP7T/vH31oy3ETCzr5WDrS0M=,tag:4tKyofWEp0+BZCJCMPl9GQ==,type:str]
    pgp: []
    encrypted_regex: ^data$
    version: 3.7.3
