apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo-creds
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/eropad/gitops.git
  username: {{ .Values.githubUsername }}
  password: {{ .Values.githubPassword }}
