apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gitops-repo-creds
spec:
    secretTemplates:
        - name: gitops-repo-creds
          labels:
            argocd.argoproj.io/secret-type: repository
          stringData:
            url: '{{ $.Values.repoUrl }}'
            username: '{{ $.Values.githubUsername }}'
          data:
            password: ENC[AES256_GCM,data:/kATL+4TWkWqCS8KOJvrCl/Xmh554kmRF09I0q9Ir3I3Fuh8ZZlPbQw3Kl+K2RaTfVs1KsAc+js=,iv:qH7u5zMfYvWwy7dCxYjfYa8JZLT/wrx2C06InFWFzYc=,tag:yin87H8lsowJRCFdWqUhvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7slh9h999g84kepruxeuf49lstcpycvzpkjek4msl2e3835gc6s5rhyzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTek9YQXRNbGxmclFVajNj
            MURrUU5KKzhtNVZjVDZnZ0VhbnJpSWFwdkZBCnBWY1JvTTdUWlEwMGhTb1pxMnZa
            QkZaaVNJVWwrOUFKMTJYaFEreVJuclUKLS0tIHZhUHEvUERYYWxuTkJJRXh5cTI4
            UEpQNVU0QUxudFovdjI4MDV5N3JjRlUKxbu0E65lzw2cULgQrLmK+KyVEfr++9n9
            VEvl0nJ0NjbxZBMZ2gv/qXnBFJg7Q1/H5p6Ycbp8OxY637O1Vh5Lcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-16T16:53:11Z"
    mac: ENC[AES256_GCM,data:fpJ7f8w3T2AJD+UZdoC4KS4Wb2yI97k4syeHqfv1a+mffzogkzluYJQ5In37z7aXpiqjqr3zt0l0HqKpbUws/mTd1DvF4igDTbVYZag0cR8ggQV7Gdj3OrrkSRoErt8MaG2jwv28sMCU8aaY/ajSsJDjGRGfzbL7VtehKO9AnU4=,iv:kcQZ1M/ZHFatDQfK+5PDEYR3PYHYBzRINyoN0Hm+w9U=,tag:W8zu+A8gUPgTuCSJR/6MUA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
