apiVersion: v1
stringData:
  AWS_SECRET_ACCESS_KEY: {{ $.Values.doSecretAccessKey }}
  AWS_ACCESS_KEY_ID: {{ $.Values.doAccessKeyId }}
  GHOST_STORAGE_ADAPTER_S3_PATH_BUCKET: {{ $.Values.doBucket }}
  GHOST_STORAGE_ADAPTER_S3_ENDPOINT: {{ $.Values.s3Endpoint }}
  GHOST_STORAGE_ADAPTER_S3_ASSET_HOST: https://{{ $.Values.doBucket }}.{{ $.Values.s3Endpoint }}
kind: Secret
metadata:
  name: s3-credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    # reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: prod-ghost, dev-ghost, staging-ghost
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: prod-ghost
