argo-cd:
  configs:
    secret:
      createSecret: false
environments:
  - prod
repoUrl: https://github.com/eropad/gitops.git
host: devops.lovelustpassion.live
githubUsername:
githubPassword:
argocdAdminPasswordBcryptHash:
