argo-cd:
  configs:
    secret:
      createSecret: false
repoUrl: repoUrl
domain: domain
githubUsername: githubUsername
githubPassword: githubPassword
argocdAdminPasswordBcryptHash: argocdAdminPasswordBcryptHash
doCreds: doCreds
mailgunAuthPass: mailgunAuthPass
doAccessKeyId: doAccessKeyId
doSecretAccessKey: doSecretAccessKey
doBucket: doBucket
s3Endpoint: s3Endpoint
region: region
