argo-cd:
  configs:
    secret:
      createSecret: false
    cm:
      create: false
environments:
  - prod
repoUrl: https://github.com/eropad/gitops.git
domain: lovelustpassion.live
githubUsername: githubUsername
githubPassword: githubPassword
argocdAdminPasswordBcryptHash: argocdAdminPasswordBcryptHash
doCreds: doCreds
