sops-secrets-operator:
  secretsAsFiles:
    - name: sops-age-key
      secretName: sops-age-key-file
      mountPath: /age-sops
  extraEnv:
    - name: SOPS_AGE_KEY_FILE
      value: /age-sops/keys.txt
external-dns:
  provider: digitalocean
  digitalocean:
    secretName: do-creds
repoUrl: https://github.com/eropad/gitops.git
domain: lovelustpassion.live
githubUsername: alias-rahil
region: region
doCreds: doCreds
ageKeys: ageKeys
