argo-cd:
  configs:
    secret:
      createSecret: false
sops-secrets-operator:
  secretsAsFiles:
    - name: sops-age-key
      secretName: sops-age-key-file
      mountPath: /age-sops
  extraEnv:
    - name: SOPS_AGE_KEY_FILE
      value: /age-sops/keys.txt
repoUrl: https://github.com/eropad/gitops.git
domain: lovelustpassion.live
githubUsername: alias-rahil
doBucket: eropad-lovelustpassion
s3Endpoint: digitaloceanspaces.com
region: region
doCreds: doCreds
ageKeys: ageKeys
