argo-cd:
  configs:
    secret:
      createSecret: false
repoUrl: repoUrl
domain: domain
githubUsername: githubUsername
githubPassword: githubPassword
argocdAdminPasswordBcryptHash: argocdAdminPasswordBcryptHash
doCreds: doCreds
