argo-cd:
  configs:
    secret:
      createSecret: false
environments:
  - prod
repoUrl: https://github.com/eropad/gitops.git
host: argo-cd.lovelustpassion.live
githubUsername: githubUsername
githubPassword: githubPassword
argocdAdminPasswordBcryptHash: argocdAdminPasswordBcryptHash
doCreds: doCreds
