on:
  schedule:
    - cron: 0 0 * * *
jobs:
  sync-state:
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: pulumi-contrib/setup-pulumi@v1
      - run: npm install
      - run: npm run pulumi:up
