on:
  push:
    branches:
      - main
      - release
jobs:
  sync-state:
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: pulumi-contrib/setup-pulumi@v1
      - run: npm install
      - if: ${{ github.ref_name }} === "main"
        run: npm run dev
      - if: ${{ github.ref_name }} === "release"
        run: npm run prod
